name: Java CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Build project and run unit and API checks
        run: mvn --batch-mode package
      - name: Run E2E checks
        run: |
          java -jar target/mot-cert-support-app-java-*-exec.jar &
          curl --head -X GET --retry 60 --retry-connrefused --retry-delay 1 http://localhost:8080
          mvn test -Dtest=LoginTest